version: 2
updates:
  # Monitora as GitHub Actions e Reusable Workflows no diretório raiz
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps-dev)"
      include: "scope"